/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutPostsRouteImport } from './routes/_layout.posts'
import { Route as LayoutPostsIndexRouteImport } from './routes/_layout.posts.index'
import { Route as LayoutPostsPostIdRouteImport } from './routes/_layout.posts.$postId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPostsRoute = LayoutPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPostsIndexRoute = LayoutPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutPostsRoute,
} as any)
const LayoutPostsPostIdRoute = LayoutPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => LayoutPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/posts': typeof LayoutPostsRouteWithChildren
  '/posts/$postId': typeof LayoutPostsPostIdRoute
  '/posts/': typeof LayoutPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/posts/$postId': typeof LayoutPostsPostIdRoute
  '/posts': typeof LayoutPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/posts': typeof LayoutPostsRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/posts/$postId': typeof LayoutPostsPostIdRoute
  '/_layout/posts/': typeof LayoutPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/posts' | '/posts/$postId' | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/posts/$postId' | '/posts'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/posts'
    | '/_layout/'
    | '/_layout/posts/$postId'
    | '/_layout/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/posts': {
      id: '/_layout/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof LayoutPostsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/posts/': {
      id: '/_layout/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof LayoutPostsIndexRouteImport
      parentRoute: typeof LayoutPostsRoute
    }
    '/_layout/posts/$postId': {
      id: '/_layout/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof LayoutPostsPostIdRouteImport
      parentRoute: typeof LayoutPostsRoute
    }
  }
}

interface LayoutPostsRouteChildren {
  LayoutPostsPostIdRoute: typeof LayoutPostsPostIdRoute
  LayoutPostsIndexRoute: typeof LayoutPostsIndexRoute
}

const LayoutPostsRouteChildren: LayoutPostsRouteChildren = {
  LayoutPostsPostIdRoute: LayoutPostsPostIdRoute,
  LayoutPostsIndexRoute: LayoutPostsIndexRoute,
}

const LayoutPostsRouteWithChildren = LayoutPostsRoute._addFileChildren(
  LayoutPostsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutPostsRoute: typeof LayoutPostsRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutPostsRoute: LayoutPostsRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
