/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as ApiUserRouteImport } from './routes/api/user'
import { Route as LayoutPostsRouteImport } from './routes/_layout.posts'
import { Route as LayoutPostsIndexRouteImport } from './routes/_layout.posts.index'
import { Route as LayoutPostsPostIdRouteImport } from './routes/_layout.posts.$postId'
import { Route as ApiPostPostIdLikeRouteImport } from './routes/api/post.$postId.like'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiUserRoute = ApiUserRouteImport.update({
  id: '/api/user',
  path: '/api/user',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPostsRoute = LayoutPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPostsIndexRoute = LayoutPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutPostsRoute,
} as any)
const LayoutPostsPostIdRoute = LayoutPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => LayoutPostsRoute,
} as any)
const ApiPostPostIdLikeRoute = ApiPostPostIdLikeRouteImport.update({
  id: '/api/post/$postId/like',
  path: '/api/post/$postId/like',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/posts': typeof LayoutPostsRouteWithChildren
  '/api/user': typeof ApiUserRoute
  '/posts/$postId': typeof LayoutPostsPostIdRoute
  '/posts/': typeof LayoutPostsIndexRoute
  '/api/post/$postId/like': typeof ApiPostPostIdLikeRoute
}
export interface FileRoutesByTo {
  '/api/user': typeof ApiUserRoute
  '/': typeof LayoutIndexRoute
  '/posts/$postId': typeof LayoutPostsPostIdRoute
  '/posts': typeof LayoutPostsIndexRoute
  '/api/post/$postId/like': typeof ApiPostPostIdLikeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/posts': typeof LayoutPostsRouteWithChildren
  '/api/user': typeof ApiUserRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/posts/$postId': typeof LayoutPostsPostIdRoute
  '/_layout/posts/': typeof LayoutPostsIndexRoute
  '/api/post/$postId/like': typeof ApiPostPostIdLikeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/api/user'
    | '/posts/$postId'
    | '/posts/'
    | '/api/post/$postId/like'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/user' | '/' | '/posts/$postId' | '/posts' | '/api/post/$postId/like'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/posts'
    | '/api/user'
    | '/_layout/'
    | '/_layout/posts/$postId'
    | '/_layout/posts/'
    | '/api/post/$postId/like'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiUserRoute: typeof ApiUserRoute
  ApiPostPostIdLikeRoute: typeof ApiPostPostIdLikeRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/user': {
      id: '/api/user'
      path: '/api/user'
      fullPath: '/api/user'
      preLoaderRoute: typeof ApiUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/posts': {
      id: '/_layout/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof LayoutPostsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/posts/': {
      id: '/_layout/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof LayoutPostsIndexRouteImport
      parentRoute: typeof LayoutPostsRoute
    }
    '/_layout/posts/$postId': {
      id: '/_layout/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof LayoutPostsPostIdRouteImport
      parentRoute: typeof LayoutPostsRoute
    }
    '/api/post/$postId/like': {
      id: '/api/post/$postId/like'
      path: '/api/post/$postId/like'
      fullPath: '/api/post/$postId/like'
      preLoaderRoute: typeof ApiPostPostIdLikeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutPostsRouteChildren {
  LayoutPostsPostIdRoute: typeof LayoutPostsPostIdRoute
  LayoutPostsIndexRoute: typeof LayoutPostsIndexRoute
}

const LayoutPostsRouteChildren: LayoutPostsRouteChildren = {
  LayoutPostsPostIdRoute: LayoutPostsPostIdRoute,
  LayoutPostsIndexRoute: LayoutPostsIndexRoute,
}

const LayoutPostsRouteWithChildren = LayoutPostsRoute._addFileChildren(
  LayoutPostsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutPostsRoute: typeof LayoutPostsRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutPostsRoute: LayoutPostsRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ApiUserRoute: ApiUserRoute,
  ApiPostPostIdLikeRoute: ApiPostPostIdLikeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
